---
title: "February 24th, 2026"
---

## Summary

Google Earth Engine (GEE) is a free (for now and for certain limited purposes) platform that serves and displays data from EO instruments programmatically, as well as providing some cloud-computing resources and built-in functions for common operations which are optimized to take advantage of running on Google's servers. Scripting in GEE requires Javascript, which is less familiar to me than Python, but also less annoying to me than R. I'll take it. According to today's lecture, LLMs are not very familiar with GEE code, since there is so much more vanilla Javascript for them to have trained on than GEE-specific code. 

Interestingly, there is some interplay between the GUI and the scripting, allowing a user to draw in polygons and select points using the mouse. 

The main task of the practical was combining multiple tiles into a mosaiced image using the median to combine multiple passes of the same tile, and the mean to combine the overlapping portions of images. Why not use something spatial to combine them, like at least an interpolation between tiles through the overlapping portion? We also reviewed band math, texture measures, and PCA using GEE. PCA in particular was much more involved than in R or Python, but not insurmountable to understand with some careful reading.

## Applications

As a demonstration of the power and potential of GEE (at the time, recently released), @noauthor_land_nodate employed it to apply an evapotranspiration method devised and tested on certain regions in the United States to the entire globe rapidly and easily. Working with derived datasets served by GEE, they could simply apply the published formula at the available resolution and compare results with *in situ* measurements collected at certain points around the world.

Around the same time, @yancho_google_2020 developed a much more involved tool in GEE: Google Earth Engine Mangrove Mapping Methodology (GEEMMM). The development of this tool involved producing generalized code to filter to areas of interest, further filter by elevation and slope, remove clouds and water, and train a random forest model to classify the landcover type with a focus on distinguishing mangrove forests from everything else. This wide variety of complexity from early on in GEE's history demonstrates it's wide appeal and versatility.

## Reflection

I'm generally excited about working with GEE. Although I'm arriving a bit later on the scene this time, it reminds me of when I first installed Google Earth on my family PC in 2005. With the massive proliferation and decentralization of EO data and analysis through GEE, it seems difficult to avoid significant duplication of effort. It may also be more difficult to verify the reliability of various analyses presented, since it's so easy for anyone to carry out.