---
title: "March 23, 2026"
---

## Summary

This final lecture concerned Synthetic Aperture Radar (SAR). Unlike the other sensors we have been working with, SAR is an active instrument. It outputs a radio wave and "listens" for the response when the reflected radio signal bounces back up to the sensor (or doesn't, as the case may be) from the surface of the Earth. The aperture is "synthetic" because the rapid motion of the satellite is used to compensate for the short length of the antenna. Different combinations of frequency and polarization are best suited for different tasks, so consulting literature and a bit of trial-and-error might be helpful in beginning any SAR-based analysis. Because the waves are not blocked by clouds and it doesn't rely on the sun for illumination, SAR data is more consistently usable. Detecting change, through many, many potential metrics seems to the most common theme behind use cases for SAR.

Interferometric synthetic aperture radar (InSAR) is where it gets really interesting. By comparing the phase of the return signal in successive passes, the difference in the elevation of surface below can be revealed (potentially plus or minus any integer number of half wavelengths). SAR data is reported as an imaginary number (generally equivalent in engineering applications to sinusoid with a certain magnitude and phase, which is both familiar and pretty cool). GEE only provides the magnitude of the return, no phase, so you need other tools to work with InSAR. The lecture says you have to use SNAP, but there are definitely Python packages for it.

## Applications

@ningthoujam_airborne_2016 evaluated predictive models of Above-Ground Biomass (AGB) in selected forests in the UK based on the S-band SAR backscatter collected from airplanes as part of the AirSAR Campaign. S-Band is considered suitable for forestry because it can penetrate through the canopy and interact with trunks and larger branches. HH and VV polarities showed the most promise, although they were both less accurate on older, higher AGB plots. Interestingly, they tended to be less accurate in opposite directions. Surely there's an obvious opportunity to construct a model that uses both HH and VV? And maybe also HV and VH?

In contrast to that application, @noauthor_environmental_2019 employed satellite SAR from ERS-1/2, ENVISAT and Sentinel-1. They used both amplitude and phase data (primarily phase) to interferometrically determine the ground height in areas potentially affected by shale gas extraction. Earlier data from ERS 1/2 and ENVISAT provide a baseline from before the extraction began and Sentinel-1 provides an ongoing years-long time series. Although there has been increased seismic activity in those areas, the overall trend of ground motion is consistent with the baseline trajectory. According to the authors, this is important to monitor because some day it might not be, and also because many people falsely believe that it isn't now (as of 2019).

## Reflection

I have used interferometric instruments fundamentally similar to InSAR, but with visible red laser light professionally to measure tiny deviations from straightness along bearing rails. It's very fiddly to set up in industrial environments, so it seems surprising at first that it works from space. Of course 5 cm is much more forgiving than 700 nm, but still it's in space. That's wild.
