---
title: "March 9, 2026"
---

## Summary

This week covered many additional methods for image classification, in particular sub-pixel methods and object-based classification. 

In the practical, we used "unmix" in GEE to generate predicted portions of each pixel belonging to each of 4 "endmembers" (then merged 2 of them into 1 for a final count of 3). When hardening the predictions to generate a confusion matrix, we were instructed to use a threshold of 50% for each of the 4 endmembers. I'm not sure I like that. It kind of seems like the classification should be selected based on whichever endmember's predicted contribution to the overall pixel is highest even if none is more than 50%. Some pixels may not be classified at all with a 50% threshold and more than 2 endmembers, right?

Object-based classification requires the clustering of close and similar pixels into groups (objects) and training a classifier on the characteristics of the objects within the image instead of on the pixels. There are many ways of clustering pixels into objects, including K-means and Simple Non-Iterative Clustering (SNIC) which we covered in the practical, but they all do generally the same process of finding groupings of similar pixels and calculating features of the combined objects. A potential advantage is that the shape characteristics of the objects can be included as features for the classification. This seems very useful for built environment classifications because of all the distinct and high-contrast shapes involved.

## Applications

Just last year a new method of combining both object-based methods and sub-pixel spectral unmixing was developed to enable unsupervised models to learn spectral signatures and un-mix them with greater resulting classification accuracy than manual specification of spectra @noauthor_unsupervised_2025. It works by taking advantage of the fact that the edges of objects are less likely to be spectrally pure. So after generating objects, their outer pixels are eroded away from consideration before their inner pixels are used to calculate a more pure spectral signature. Then those signatures can be used as endmembers in a standard unmixing algorithm either on objects or pixel-wise. 

Advantages of object-based approaches to classification have been documented for years, especially in certain contexts. @noauthor_comparison_nodate found that object-based classifications were more accurate, more transferable, and less in need of manual corrections to remove stray misclassifications in the context of mapping the extents of glacial ice, especially when the glaciers have debris or lakes on top of them. I'm curious whether employing the unsupervised unmixing along with some logic concerning classes of things which can be on top of glaciers might yield any improvement.

## Reflection

"Sub-pixel methods" in this context has a bit of a different meaning from what I've encountered before. It's a similar idea but the goal is to un-mix the spectral signatures that could have combined to produce each pixels' overall spectrum, whereas I knew it as a way of measuring the size or position of an object within a photograph with greater precision than the size of a pixel. Both rely on the assumption that the overall value of each channel is a linear combination of two or more different true values scaled by the proportion of the area of the pixel covered by the types of things which produce those true values. 

I did a slightly simpler version of the same thing as @noauthor_unsupervised_2025 at work in 2023 to distinguish sufficiently and insufficiently carbonized biochar in an inspection cell. Objects of belt, carbonized wood, and uncarbonized wood were generated with kmeans and then pixels were weighted by their distance from object boundaries to calculated weighted mean spectral signatures for each of the k=3 classes. It worked great in that context too. Maybe thousands (or even tens or hundreds of thousands) of people have independently implemented that same general idea in their own specific circumstances but not bothered to write a paper about it.

