---
title: "March 2, 2026"
---

## Summary

Classic image segmentation techniques (Classification and Regression Tree, Random Forest, Naive Bayes and Support Vector Machines) are available for use in Google Earth Engine, on up to 1,000,000 points at a time. 1,000,000 is really not many. That's a 1MP photo, like a mobile phone camera as old as some of the students in the program. I used to work with at least 5MP industrial machine vision cameras, and sometimes trained models for those images on a laptop. It seems Google is not being particularly generous with the cloud computing resources, but it should at least be fast to train.

Training machine learning models in general required reserving some (here 30%, but I've seen less than that in other contexts) of the data as a test set (and sometimes further reserving more data as a validation set, although we didn't explicitly do this in the practical). A major difference could be observed in performance when the test-train split was done on the polygon level or on the individual pixel level. I expected pixel-wise to be better, but I did not expect such a stark difference. I noticed that there's a totally obvious error in the code for the polygon-wise split too, which might be part of the issue. The split is actually 50/50 rather than 70/30, so the model is only getting to see half of the data.

```{}
// // --------------------- train, test split --------------------------------

// We want to reserve some of the data for testing, to avoid overfitting the model.
var split = 0.5;  // Roughly 70% training, 30% testing.
//           ↑
//     THIS HERE IS WRONG


var trainingPartition = withRandom.filter(ee.Filter.lt('random', split));
var testingPartition = withRandom.filter(ee.Filter.gte('random', split));
```

## Applications

[citation] tested a total of 10 different classification models available in GEE on the typical EO analysis task of land use classification for the purpose of comparison between them. CART performed the best with Random Forest and Voting SVM not far behind. They concluded that the more complex models could benefit from larger training sets, but within the constraints of the available resolution and GEE's limitations simpler ones prevailed and performed pretty well.

@choudhary_random_2022 elected to use a a Random Forest model on Sentinel-2 data from GEE to predict rice yield from small farms in Guangdong Province, China. Lots of field work was involved in collecting the actual status of the rice fields, which was supported by the Guangdong Department of Agriculture. They used much more than 1000000 points and had to train the model outside of GEE, but achieved much more accurate results on test data than linear or single decision tree models. Maybe even the Random Forest model is complex enough to suffer from the limited training data allowed by GEE. 

## Reflection

I really enjoy thinking about all the different types of models the relationships between them, since they're all ultimately doing the same thing (splitting the feature space by predicted classes) but with different assumptions about the shape and firmness of the boundaries between them. In my (admittedly limited) experience with machine learning, XGBoost has been able to do anything Random Forest can do better than Random Forest can. Why is it not available in GEE? Why is is seemingly not so popular in remote sensing applications generally? 
